'use client';

import * as React from 'react';

export default function EventsPage() {
  return (
    <div className="bg-blue-500 text-white min-h-screen">
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat exercitationem distinctio et quasi dolorum corporis adipisci qui quibusdam commodi velit, suscipit voluptatem perferendis? Praesentium nostrum beatae quam rem asperiores possimus? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, labore deleniti. Laborum dignissimos corporis nesciunt suscipit optio similique libero, expedita vel in earum? Ad illum nihil quisquam autem, beatae libero? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab, quia odio? Cumque ab a impedit sit repellat quae laudantium, accusantium pariatur aspernatur harum ipsa laborum, voluptas quisquam odit voluptatibus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum tenetur itaque quo enim deleniti, hic delectus corporis obcaecati, harum, unde maiores. Deserunt ducimus eius itaque sit ex, eveniet impedit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad voluptatum, eligendi possimus exercitationem id quibusdam sapiente cupiditate similique temporibus nobis excepturi ipsam eius consectetur ut quidem hic autem asperiores aperiam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Animi quod voluptatibus accusantium expedita laudantium! Quidem placeat cum harum eius eum natus minima quod repudiandae earum? Necessitatibus praesentium obcaecati dicta nulla? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea laudantium sint, dolorum omnis assumenda perspiciatis laboriosam debitis sapiente ipsa, cum fugit facilis reprehenderit enim voluptates modi officia iste nemo repellendus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil magnam totam voluptate harum perferendis, temporibus cumque. Dolor earum iusto neque excepturi esse, consequatur atque quos est exercitationem qui accusantium expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti ex corporis hic quisquam id, earum ipsam pariatur debitis maxime sunt voluptates, nihil repudiandae necessitatibus, adipisci possimus aperiam praesentium. Assumenda, cum.. Voluptatem velit odio maxime cumque labore. Facilis esse itaque, odio consequatur sunt molestiae dolores nulla nobis expedita impedit repellendus neque assumenda vel! Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ullam et voluptatem. Eveniet dignissimos molestias excepturi quaerat numquam, libero error aperiam sint, facilis doloremque quam magni itaque deleniti nulla amet!</h1>
    </div>
  );
}
